<!DOCTYPE HTML>
<html>
<head>
  <title>PHPDoc2 - PHPUnit</title>
  <link rel="stylesheet" type="text/css" href="default.css">
</head>
<body>
<nav>
  <a href="index.html">Root</a>
</nav>

<div class="content">
<ul><li>\PHPUnit_Framework_TestFailure</li></ul>
<h1>
  <small>class</small>

  <a href="namespace_.html" class="">(none)</a>  \
  <a href="class__PHPUnit_Framework_TestFailure.html" class="">PHPUnit_Framework_TestFailure</a></h1>




<hr>

<p>A TestFailure collects a failed test together with the caught exception.</p><dl></dl>
<hr>

<h2>Method Summary</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
<tr><td><a href="class__PHPUnit_Framework_TestFailure.html#__construct" class="">__construct(PHPUnit_Framework_Test $failedTest, Exception $thrownException)</a></td><td>Constructs a TestFailure with the given test and exception.</td></tr><tr><td><a href="class__PHPUnit_Framework_TestFailure.html#exceptionMessage" class="">exceptionMessage()</a></td><td>Returns the exception's message.</td></tr><tr><td><a href="class__PHPUnit_Framework_TestFailure.html#exceptionToString" class="">exceptionToString(Exception $e)</a></td><td>Returns a description for an exception.</td></tr><tr><td><a href="class__PHPUnit_Framework_TestFailure.html#failedTest" class="">failedTest()</a></td><td>Returns the failing test.</td></tr><tr><td><a href="class__PHPUnit_Framework_TestFailure.html#getExceptionAsString" class="">getExceptionAsString()</a></td><td>Returns a description for the thrown exception.</td></tr><tr><td><a href="class__PHPUnit_Framework_TestFailure.html#getTestName" class="">getTestName()</a></td><td>Returns the name of the failing test (including data set, if any).</td></tr><tr><td><a href="class__PHPUnit_Framework_TestFailure.html#isFailure" class="">isFailure()</a></td><td>Returns true if the thrown exception is of type AssertionFailedError.</td></tr><tr><td><a href="class__PHPUnit_Framework_TestFailure.html#thrownException" class="">thrownException()</a></td><td>Gets the thrown exception.</td></tr><tr><td><a href="class__PHPUnit_Framework_TestFailure.html#toString" class="">toString()</a></td><td>Returns a short description of the failure.</td></tr>  </tbody>
</table>



<hr>

<h3>
  <small>public function</small>
  __construct(<a href="interface__PHPUnit_Framework_Test.html" class="">PHPUnit_Framework_Test</a> $failedTest, Exception $thrownException)  <a name="__construct"></a>
</h3>

<blockquote>
<p>Constructs a TestFailure with the given test and exception.</p><dl><dt>Parameters:</dt><dd><code>PHPUnit_Framework_Test</code> - $failedTest<br><code>Exception</code> - $thrownException<br></dd></dl></blockquote>


<hr>

<h3>
  <small>public function</small>
  exceptionMessage()  <a name="exceptionMessage"></a>
</h3>

<blockquote>
<p>Returns the exception's message.</p><dl><dt>Returns:</dt><dd>string<br></dd></dl></blockquote>


<hr>

<h3>
  <small>public static function</small>
  exceptionToString(Exception $e)  <a name="exceptionToString"></a>
</h3>

<blockquote>
<p>Returns a description for an exception.</p><dl><dt>Parameters:</dt><dd><code>Exception</code> - $e<br></dd><dt>Returns:</dt><dd>string<br></dd></dl></blockquote>


<hr>

<h3>
  <small>public function</small>
  failedTest()  <a name="failedTest"></a>
</h3>

<blockquote>
<p>Returns the failing test.</p><p>Note: The test object is not set when the test is executed in process isolation.</p><dl><dt>Returns:</dt><dd>PHPUnit_Framework_Test|null<br></dd><dt>See Also:</dt><dd><a href="class__PHPUnit_Framework_Exception.html" class="">PHPUnit_Framework_Exception</a><br></dd></dl></blockquote>


<hr>

<h3>
  <small>public function</small>
  getExceptionAsString()  <a name="getExceptionAsString"></a>
</h3>

<blockquote>
<p>Returns a description for the thrown exception.</p><dl><dt>Returns:</dt><dd>string<br></dd></dl></blockquote>


<hr>

<h3>
  <small>public function</small>
  getTestName()  <a name="getTestName"></a>
</h3>

<blockquote>
<p>Returns the name of the failing test (including data set, if any).</p><dl><dt>Returns:</dt><dd>string<br></dd></dl></blockquote>


<hr>

<h3>
  <small>public function</small>
  isFailure()  <a name="isFailure"></a>
</h3>

<blockquote>
<p>Returns true if the thrown exception is of type AssertionFailedError.</p><dl><dt>Returns:</dt><dd>boolean<br></dd></dl></blockquote>


<hr>

<h3>
  <small>public function</small>
  thrownException()  <a name="thrownException"></a>
</h3>

<blockquote>
<p>Gets the thrown exception.</p><dl><dt>Returns:</dt><dd>Exception<br></dd></dl></blockquote>


<hr>

<h3>
  <small>public function</small>
  toString()  <a name="toString"></a>
</h3>

<blockquote>
<p>Returns a short description of the failure.</p><dl><dt>Returns:</dt><dd>string<br></dd></dl></blockquote>

</div>

<div class="footer">
  Generated by <a href="https://github.com/soundasleep/phpdoc2/" class="github">PHPDoc2</a> Fri, 24 Apr 2015 15:28:57 +1200</div>

</body>
</html>
